# Generated by Django 3.1.7 on 2021-04-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
